# Generated by Django 2.0.5 on 2018-07-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoPastebin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.IntegerField()),
                ('link', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=256)),
                ('user', models.CharField(max_length=256)),
                ('language', models.CharField(choices=[('text', 'TEXT'), ('c', 'C'), ('cpp', 'C++'), ('py', 'PYTHON'), ('json', 'JSON')], default='text', max_length=5)),
                ('image', models.FileField(blank=True, default='templates/upload_pictures/noimage.png', max_length=256, null=True, upload_to='templates/upload_pictures')),
                ('video', models.FileField(blank=True, default='templates/upload_pictures/no-video.jpg', max_length=256, null=True, upload_to='templates/upload_videos')),
                ('created', models.DateTimeField(auto_now=True)),
                ('expiry', models.IntegerField(choices=[(1, '1 Day'), (7, '1 Week'), (30, '1 Month'), (365, '1 Year')], default=1)),
            ],
        ),
    ]
